### PR TITLE
add support for qatarcentral region

### PR DESCRIPTION
**Pull request by yohanhounsounou**
Fixes #(issue) .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Changes proposed in this pull request

- https://github.com/claranet/terraform-azurerm-regions/issues/9

@claranet/fr-azure-reviewers

### CODE REVIEW

**Review by Shr3ps — APPROVED** [review]

**Review by jmapro — APPROVED** [review]
LGTM

**Comment by yohanhounsounou** [comment]
Hello guys, is it possible to merge ? Thanks

**Comment by yohanhounsounou** [comment]
Hello guys, is it possible to merge ? Thanks

**Comment by yohanhounsounou** [comment]
Hello, 
could you please create a new tag including the latest updates ?
Thanks

**Comment by Shr3ps** [comment]
Next release will be pushed when internal others changes will be reviewed.

**Pull request merged**
